# Generated by Django 3.2.2 on 2021-05-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='price',
            new_name='prices',
        ),
    ]
