# Generated by Django 3.2.2 on 2021-05-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_rename_price_destination_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='prices',
        ),
    ]
