# Generated by Django 3.2.2 on 2021-05-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_destination_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
